openssl: use ERR_clear_error() all over the place
OpenSSL uses an error *queue* which is basically the opposite of how
errno works. ERR_get_error() reports the *earliest* error, whereas in
all cases, what glib-networking actually wants is the *most recent*
error: otherwise, we could be reporting the wrong error message for a
failed operation. Accordingly, we should clear the error queue before
performing any operation that could result in an error.

For example, say Operation A results in two errors. glib-networking
calls ERR_get_error() once to get the error code, popping it off the
error queue, and then creates a GError for that and reports it back to
the API user. There's still one more error left in the error queue. When
a second operation, Operation B, fails in the future, glib-networking
would again call ERR_get_error(), this time theoretically getting the
wrong error code from earlier rather than the error code corresponding
to the actual failure of Operation B.

I don't particularly like clearing the error queue, since it feels like
it could potentially cause us to hide or miss errors. But I suppose
that's unlikely, provided we carefully check for errors after each
operation like we are supposed to.

There is another option: we could use ERR_peek_last_error() instead.
This might be a better fit for glib-networking because it matches the
semantics of errno, which is what we always want. But it would also
potentially allow the error queue to continuously increase in size, so
clearing seems better.

In practice, I'm not sure how much these changes actually matter,
because in theory errors should be rare, and a single error probably
generally means the connection is thereafter unusable. But it's good to
be theoretically correct.